import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Providers from "./providers";
import QueryProvider from "@/providers/query-provider";
import { Toaster } from "@/components/ui/sonner";
// import { Manrope } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins", // Define a CSS variable for easier use
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

// const manrope = Manrope({
//   subsets: ["latin"],
//   display: "swap",
//   variable: "--font-manrope", // Define a CSS variable for easier use
//   weight: ["200", "300", "400", "500", "600", "700", "800"],
// });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
      <body className={`${poppins.variable} antialiased bg-background`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <Providers>
            <QueryProvider>{children}</QueryProvider>
            <Toaster position="bottom-right" expand={false} richColors />
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
