import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const popins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins", // Define a CSS variable for easier use
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${popins.variable} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
